### PR TITLE
Download latest release

### PR DESCRIPTION
**Pull request by HeDo88TH**
Now it downloads the latest available release from github. We should ensure that the first file in the release is the linux one.
We need to update the docs to reflect the changes: from `sh get-ddb.sh` to `bash get-ddb-sh`

### CODE REVIEW

**Review by pierotofy — COMMENTED** [review]
The problem with this PR is that this only works on Debian/Ubuntu. The script is meant to be compatible with most distros, not just Ubuntu.

**Comment by HeDo88TH** [comment]
This PR simply makes the script download the latest version available. It does not change the overall behaviour of the installer

**Comment by pierotofy** [comment]
No, it breaks the installer for non-Ubuntu distro.

```
D:\>docker run -ti --rm fedora
[root@5875ecc5919e /]# vi install.sh
[root@5875ecc5919e /]# bash install.sh
# Executing DroneDB install script
install.sh: line 34: apt-get: command not found
```

This works fine with the current script:

```
[root@5875ecc5919e /]# curl https://get.dronedb.app > install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2740  100  2740    0     0  13300      0 --:--:-- --:--:-- --:--:-- 13300
[root@5875ecc5919e /]# sh install.sh
# Executing DroneDB install script
# Downloading https://github.com/DroneDB/DroneDB/releases/download/v0.9.2/ddb-0.9.2-linux.tgz...
# Extracting...
# Setting up...
# Removing previous version of ddb...
# Adding ~/.local/ddb/bin to PATH in .bashrc
# Cleaning up...

    ____                        ____  ____
   / __ \_________  ____  ___  / __ \/ __ )
  / / / / ___/ __ \/ __ \/ _ \/ / / / __  |
 / /_/ / /  / /_/ / / / /  __/ /_/ / /_/ /
/_____/_/   \____/_/ /_/\___/_____/_____/

Type: ddb --help or visit https://docs.dronedb.app to get started!

[root@5875ecc5919e /]#
```

**Comment by pierotofy** [comment]
You should also not modify these files directly; this repository is automated via a workflow on DroneDB/DroneDB. Change https://github.com/DroneDB/DroneDB/blob/master/scripts/linux_install_script.sh instead

**Comment by pierotofy** [comment]
Imo, the way to do this is to fill-in the release version from the github workflow automation using a template and `envsubst` https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html

**Pull request closed without merging**
